input.onGesture(Gesture.Shake, function () {
    number = randint(0, 3)
    if (number == 0) {
        basic.showString("7:00")
        basic.showString("well done")
    } else if (number == 1) {
        basic.showString("8:00")
        basic.showString("hurry")
    } else if (number == 2) {
        basic.showString("9:00")
        basic.showString("you late")
    } else if (number == 3) {
        basic.showString("10:00")
        basic.showString("You're a lazy")
    }
})
let number = 0
basic.showString("wake up ")
servos.P0.setAngle(0)
music.playTone(262, music.beat(BeatFraction.Whole))
servos.P0.setAngle(10)
music.playTone(262, music.beat(BeatFraction.Whole))
servos.P0.setAngle(20)
music.playTone(294, music.beat(BeatFraction.Whole))
servos.P0.setAngle(30)
music.playTone(294, music.beat(BeatFraction.Whole))
servos.P0.setAngle(40)
music.playTone(330, music.beat(BeatFraction.Whole))
servos.P0.setAngle(50)
music.playTone(262, music.beat(BeatFraction.Whole))
servos.P0.setAngle(60)
music.playTone(262, music.beat(BeatFraction.Whole))
servos.P0.setAngle(70)
music.playTone(294, music.beat(BeatFraction.Whole))
servos.P0.setAngle(80)
music.playTone(262, music.beat(BeatFraction.Whole))
servos.P0.setAngle(90)
music.playTone(294, music.beat(BeatFraction.Whole))
servos.P0.setAngle(100)
music.playTone(330, music.beat(BeatFraction.Whole))
servos.P0.setAngle(110)
music.playTone(262, music.beat(BeatFraction.Whole))
servos.P0.setAngle(120)
music.playTone(330, music.beat(BeatFraction.Whole))
servos.P0.setAngle(130)
music.playTone(330, music.beat(BeatFraction.Whole))
servos.P0.setAngle(140)
music.playTone(349, music.beat(BeatFraction.Whole))
servos.P0.setAngle(150)
music.playTone(349, music.beat(BeatFraction.Whole))
servos.P0.setAngle(160)
music.playTone(392, music.beat(BeatFraction.Whole))
servos.P0.setAngle(170)
music.playTone(330, music.beat(BeatFraction.Whole))
servos.P0.setAngle(180)
